### ISSUE TITLE
Prodcution

### ISSUE THREAD

**Issue by boukar10** [mjtiempo/markmeet#1]
Hi Mario,
Kindly is it possible to use this markmeet in production?
Please can you help to deploy it?
Thanks

**Comment by boukar10** [comment]
Hi Mark, please can you help? 
I create a service wsgi.service to start the service automatically but I'm getting the following error

sudo systemctl enable wsgi.service
The unit files have no installation config (WantedBy, RequiredBy, Also, Alias
settings in the [Install] section, and DefaultInstance for template units).
This means they are not meant to be enabled using systemctl.
Possible reasons for having this kind of units are:
1) A unit may be statically enabled by being symlinked from another unit's
   .wants/ or .requires/ directory.
2) A unit's purpose may be to act as a helper for some other unit which has
   a requirement dependency on it.
3) A unit may be started when needed via activation (socket, path, timer,
   D-Bus, udev, scripted systemctl call, ...).
4) In case of template units, the unit is meant to be enabled with some
   instance name specified.

**Comment by boukar10** [comment]
Hi Marko
If you are offering paid service, I may use your expertise to achieve my project.
Thanks

**Comment by mjtiempo** [comment]
@boukar10 markmeet is created for demo purposes only to showcase how to use jistsi with jwt authentication. Let me know how to contact you if you need further help with your project.

**Comment by boukar10** [comment]
Hi Mark
Thank you for the answer.
please can you add me on skype?
my Id is boukar10 or boukar10@yahoo.fr
Thanks a lot

**Comment by boukar10** [comment]
Hello Mark,
Please can you add me on skype or share with me your contact?
I really need your help.
Thanks
